theme: jekyll-theme-cayman
title: gemstone.common
description: GPA Gemstone Common Library
github:
  repository_name: Gemstone.Common
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji
